### ISSUE TITLE
The player name when leaving shows then their id?

### ISSUE THREAD

**Issue by ProsperCraft** [FabioZumbi12/SEDiscordBridge#11]
![c03aee942aa8223d0c4943c01f15fcda](https://user-images.githubusercontent.com/4427684/43051749-5a1b5cc6-8ddb-11e8-9ac0-675fad42b1af.png)

Using the version 1.3.4

**Comment by doublee313** [comment]
Same issue. Discord coding change?

**Comment by SplenectomY** [comment]
Could probably just prevent this from happening with a regex check for "ID:\d+" before the message is sent. I might do a pull request later if this isn't patched soon.

**Comment by FabioZumbi12** [comment]
Its fixed on latest build posted on Torch plugins channel

**Comment by doublee313** [comment]
Thx guys!

**Comment by SplenectomY** [comment]
Here's the pull request. Thoughts appreciated https://github.com/FabioZumbi12/SEDiscordBridge/pull/13

**Comment by FabioZumbi12** [comment]
People who forked SEDB fixed all know bugs, just try ;)
