### ISSUE TITLE
Feature Request.

### ISSUE THREAD

**Issue by omega117** [FabioZumbi12/SEDiscordBridge#19]
Option to have the bot remove all commands messages, not only its own response.
Option for commands and server status to keep only the last X messages or delete messages older than X days.
Option to keep bot alive/online when torch runs. but the SE server is stopped.

**Comment by FabioZumbi12** [comment]
I think you need other bot like Mee6 or some other bot message manager. And about torch offline, theres no way since the but runs on torch server.
