### ISSUE TITLE
Server start status

### ISSUE THREAD

**Issue by Conjuro** [FabioZumbi12/SEDiscordBridge#2]
https://github.com/FabioZumbi12/SEDiscordBridge/blob/fe0af5424bfde40f16956e980452453c94adf989/SEDiscordBridge/DiscordBridge.cs#L59

Server start status message goes to chat channel instead of assigned status channel.

**Comment by FabioZumbi12** [comment]
Thanks, i'll fix <3

**Comment by FabioZumbi12** [comment]
Fixed on https://github.com/FabioZumbi12/SEDiscordBridge/commit/418eeaa73bc9306f5ded9f4e725ea8b0dfdc827c
