### ISSUE TITLE
No names on game

### ISSUE THREAD

**Issue by Psychos** [FabioZumbi12/SEDiscordBridge#23]
From discord to server, no name is displayed, the tag (p) does not seem to work.

**Comment by FabioZumbi12** [comment]
Using `{p}`, not `(p)`, is not working?

**Comment by Psychos** [comment]
I have this (by default) : [D]{p}
Not Working. I see this ingame "[D]Discord: Message"
No nickname.

**Comment by smooreace** [comment]
Same here

Configured to use    [D]{p}

https://gyazo.com/8f735b6cc51f8fb25dc117f61897522d

**Comment by FabioZumbi12** [comment]
Humm, probally a Torch or game update have break this. I'll check this later!

**Comment by smooreace** [comment]
Cant be Torch!! They dont do anything wrong!

**Comment by FabioZumbi12** [comment]
No more people having this issue (i've asked on discord torch), and seems to not have console errors, its hard to know whats the problem! This problem stills?

**Comment by Sadragos** [comment]
I could reproduce this Bug: When you check "Use Discord nicknames" and the person does not use a nickname {p} does not return anything. Maybe there needs to be a fallback if there's no nickname set (and the person uses its default discord username) that the username should be used instead

**Comment by intel352** [comment]
@FabioZumbi12 agreed w/ @Sadragos, issue is when the nickname option is enabled. Need Discord username as fallback for nickname not existing.

**Comment by FabioZumbi12** [comment]
Try this build please.
[SEDiscordBridge.zip](https://github.com/FabioZumbi12/SEDiscordBridge/files/3126654/SEDiscordBridge.zip)

**Comment by William0216** [comment]
Also having this issue on Version 2.0.2.5, as previously suggested by @Sadragos disabling the nickname usage worked

**Comment by FabioZumbi12** [comment]
Support moved to https://torchapi.net/plugins/item/3cd3ba7f-c47c-4efe-8cf1-bd3f618f5b9c
