### ISSUE TITLE
SEDiscordBridge seems to prevent Server Restarts

### ISSUE THREAD

**Issue by LordTylus** [FabioZumbi12/SEDiscordBridge#24]
Hello there,

I noticed something funny on our server since the installation of SEDiscordBridge

We have an increased amount of restarts not working properly. I was unsure what exactly it may causing but the logs dont show the DiscordBridgePlugin being unloaded when restart does not work, So I assume it has something to do with that:

Restart at 4AM which worked fine
> 04:00:03.3113 [INFO]   ConcealGroup: Grid group 'Kropeks Place' was marked for close.
04:00:03.3113 [INFO]   ConcealGroup: Grid group '(NPC-SOC) DBS Observation Outpost' was marked for close.
04:00:04.9456 [INFO]   Torch.Session.TorchSessionManager: Unloaded torch session for Star System, 3 Planets, Moons and Asteroids
04:00:05.0611 [WARN]   SEDiscordBridge.SEDiscordBridgePlugin: Discord Bridge Unloaded!
04:00:05.5023 [INFO]   Torch: Server stopped.

Restart at 8AM which failed
> 08:00:03.4108 [INFO] ConcealGroup: Grid group 'Static Grid 8110' was marked for close.
08:00:03.4108 [INFO]   ConcealGroup: Grid group 'Large Grid 2592' was marked for close.
08:00:04.8810 [INFO]   Torch.Session.TorchSessionManager: Unloaded torch session for Star System, 3 Planets, Moons and Asteroids
08:02:02.5833 [INFO]   ALE_RestartWatchdog.RestartManager: Shutdown successful no need to interfere!
08:47:59.1687 [INFO]   Torch: Stopping server.
08:48:21.0549 [INFO]   Torch: Stopping server.

I am also using my RestartWatchdog as you can see in these Logs. It force kills the server in case Unloading takes too long (Sometimes Torch seem to freeze). But in this instance it seems like Torch reached the Unloaded state correctly. which is why no force restart was necessary 

but the DiscordBridge was not unloaded.

What other information are needed? Could you take a look at it?

Could it be that
```
        public void Stopdiscord()
        {
            DisconnectDiscord().ConfigureAwait(false).GetAwaiter().GetResult();
        }
```

Is somehow blocking?

I also noticed that I cannot really kill the server. It cannot be started again and closing the UI using the X is also not possible. I need to hard kill the whole process using the Task Manager.

**Comment by ghost** [comment]
Hey, I totally support this bug, we have had many unsuccessful restart over time since we have this wonderful plugin ...

Failed restart logs : 
```
16:01:07.8462 [INFO]   ConcealGroup: Grid group ' TOR.Base1' was marked for close.
16:01:07.8462 [INFO]   ConcealGroup: Grid group 'Container MK-12' was marked for close.
16:04:05.4371 [INFO]   Torch.Session.TorchSessionManager: Unloaded torch session for [EU 24/7] Powered by Torch
16:21:11.8319 [INFO]   SteamCMD: Checking for DS updates.
```

16:21 is a manual restart launched


Normal restart logs : 

```
20:00:47.2092 [INFO]   ConcealGroup: Grid group 'Large Grid 7218, Large Grid 1223, was.miningship123, Large Grid 7260' was marked for close.
20:03:12.0582 [INFO]   Torch.Session.TorchSessionManager: Unloaded torch session for [EU 24/7] Powered by Torch
20:03:12.1695 [WARN]   SEDiscordBridge.SEDiscordBridgePlugin: Discord Bridge Unloaded!
20:03:16.6995 [INFO]   Torch: Server stopped.
```

I hope it can be fixed :)

Great job tho !

**Comment by smooreace** [comment]
Ive had START issues since day 1. But its all a Torch issue. I have never
had a problem with shutdowns though.

**Comment by FabioZumbi12** [comment]
Probally is DSharp issue. I need to check with dsharp devs about this.

**Comment by FabioZumbi12** [comment]
Try the last version https://torchapi.net/plugins/item/3cd3ba7f-c47c-4efe-8cf1-bd3f618f5b9c

Theres some additions and i think the reboot problem is fixed!

**Comment by smooreace** [comment]
Nope... same issues. They refuse to accept it's Torch. Typical for them
though. If they can't figure it out it must be someone else's fault.

**Comment by LordTylus** [comment]
Hi,

this noon I installed the new version on our servers and noticed that the logs are different now. 

So far unloading worked on all servers perfectly. Also when its not configured yet (as on our third server) it wont need to unload because it will not even be loaded due to missing config.

```
16:01:12.2251 [INFO]   Torch.Session.TorchSessionManager: Unloaded torch session for Star System, 3 Planets, Moons and Asteroids
16:01:12.2251 [INFO]   SEDiscordBridge.SEDiscordBridgePlugin: Unloading Discord Bridge!
16:01:12.2251 [INFO]   SEDiscordBridge.SEDiscordBridgePlugin: Discord Bridge Unloaded!
16:01:14.8301 [INFO]   Torch: Server stopped.
```

I contacted you in discord regarding new warnings in Logs like
```
20:50:37.2031 [WARN]   SEDiscordBridgePlugin: Target: 230210195830361130
20:50:45.1325 [INFO]   Chat: [Global:0] Akilae: im in orbit, my beacon is on
20:50:45.1325 [WARN]   SEDiscordBridgePlugin: Target: 0
20:50:46.5760 [INFO]   Keen: Modular Encounters Spawner: Player Hasn't Traveled Far Enough Yet.
20:50:50.8132 [INFO]   Chat: [Global:0] Dennis: I see you.
20:50:50.8132 [WARN]   SEDiscordBridgePlugin: Target: 0
```

So far all servers work as I expect them to. Ill update you tomorrow after a few more restarts if the issue occurred again. 

@smooreace: Instead of complaining you could start for example sharing some information or log files about the issues you are having.

**Comment by FabioZumbi12** [comment]
@smooreace this update is not for your problem, since you have sayd your problem is with Torch start.

Yeah Lord, I need to remove some debug messages and good to know unloading is working!! SEDB now support load and unload without needing the server is running, then to this be possible SEDB need to still listening for load and unload torch events, but this is enought, nothing more.

**Comment by smooreace** [comment]
No... I was here to start with just to mention that I wasnt having issues
with SEDB unloading. Its been running great since your help with the
running under Win 7!

**Comment by LordTylus** [comment]
HI,

short update from my point of view this can be closed. (which I am doing now) because it works fine for me for 2 days now. 

Thank you :-)
