### ISSUE TITLE
Server Messages Now Showing Up in Discord

### ISSUE THREAD

**Issue by Mr-Mors** [FabioZumbi12/SEDiscordBridge#25]
This just started today for my server, but I'm not sure when it actually got updated to the most recent version. As of today all server messages, like messages sent via essentials to everyone are now also showing up in the Discord chat channel. This was not the case earlier on this server, and I have not seen this on other servers I have played on in the past.

![image](https://user-images.githubusercontent.com/47770376/56172603-d7720480-5faf-11e9-8bd2-7420d641925a.png)

**Comment by FabioZumbi12** [comment]
Its a new option enabled by default. Check the new option after ServerName config and disable then if you dont want this.

**Comment by Mr-Mors** [comment]
Auto update from Torch had a bad download. Got all new options except that check box. There is a 20% size difference in the zip files between GitHub and what Torch had downloaded. Issue is resolved. Thanks.
