### ISSUE TITLE
Server not response after every command

### ISSUE THREAD

**Issue by Bishbash777** [FabioZumbi12/SEDiscordBridge#26]
After each command fed to a server i get a response of 'server not running' even though the server is fully functional.

![image](https://user-images.githubusercontent.com/50243964/57151832-d91e3380-6dc9-11e9-86b0-1022c4b3d3af.png)

**Comment by FabioZumbi12** [comment]
[SEDiscordBridge.zip](https://github.com/FabioZumbi12/SEDiscordBridge/files/3160397/SEDiscordBridge.zip)
Try this version.

**Comment by Bishbash777** [comment]
> [SEDiscordBridge.zip](https://github.com/FabioZumbi12/SEDiscordBridge/files/3160397/SEDiscordBridge.zip)
> Try this version.

I get "command not found" after excecuting previously working commands.

**Comment by FabioZumbi12** [comment]
Fixed on 1.5.7 (https://torchapi.net/plugins/item/3cd3ba7f-c47c-4efe-8cf1-bd3f618f5b9c)
