### ISSUE TITLE
bot truncating the first letter in all commands

### ISSUE THREAD

**Issue by tombomb** [FabioZumbi12/SEDiscordBridge#27]
The bot dosn't seem to work right, im using the version from 
https://github.com/FabioZumbi12/SEDiscordBridge/issues/23
because I was having the same issue but the issue was happening before and after updating to that version
![image](https://user-images.githubusercontent.com/544509/57371053-5f829e80-7157-11e9-99d8-8b9305d6ac54.png)
![image](https://user-images.githubusercontent.com/544509/57371191-b8eacd80-7157-11e9-8eb1-10ccca5dfa1a.png)

**Comment by FabioZumbi12** [comment]
Try to use other char, not $

**Comment by tombomb** [comment]
The first message got deleted before i could take the screen shot, but it happens for all triggers i use

![image](https://user-images.githubusercontent.com/544509/57412349-06962300-71b6-11e9-81a3-50e08ed31b3d.png)
![image](https://user-images.githubusercontent.com/544509/57412441-4d841880-71b6-11e9-9d04-a7cdc800e439.png)

**Comment by FabioZumbi12** [comment]
[SEDiscordBridge.zip](https://github.com/FabioZumbi12/SEDiscordBridge/files/3160329/SEDiscordBridge.zip)

Try this version.

**Comment by tombomb** [comment]
That one fixed it, thanks!
