### ISSUE TITLE
[Not really an issue] don't send restart countdown to Discord 

### ISSUE THREAD

**Issue by radum706** [FabioZumbi12/SEDiscordBridge#28]
Hi! thanks for your plugin and great work, first!
I wonder if you could add a way to filter some of the messages based on user or based on structure.
For example, my Discord members are complaining spamming the chat with notifications every time the server restarts (example below). 

it's just a simple if rule, i think [if (user!=="Server") or if(!msg==%"ignore message"%), i'm just a php programmer]

Thanks again!

:rocket: Server: Restarting server in 10 seconds.
:rocket: Server: Restarting server in 9 seconds.
:rocket: Server: Restarting server in 8 seconds.
:rocket: Server: Restarting server in 7 seconds.
:rocket: Server: Restarting server in 6 seconds.
:rocket: Server: Restarting server in 5 seconds.
:rocket: Server: Restarting server in 4 seconds.
:rocket: Server: Restarting server in 3 seconds.
:rocket: Server: Restarting server in 2 seconds.
:rocket: Server: Restarting server in 1 second.
:x: Server Stopped!

**Comment by FabioZumbi12** [comment]
You can disable here: 
![image](https://user-images.githubusercontent.com/5833818/58403681-b0d8cc00-8039-11e9-8bc3-0e3c81a4fcae.png)
