### ISSUE TITLE
Bot commands

### ISSUE THREAD

**Issue by daneleo** [FabioZumbi12/SEDiscordBridge#37]
I was just wondering, as I didn't want to PM you on discord or anything, seen as I don't know how to contact you on there anyways, we have several servers and wanted to know if we were allowed to modify the code so it can accept bot commands from other bots, like for example if our bot sent a server command it would register it as a user sending it instead of ignoring the bot.
Apologies for posting it here just didn't know any other way of contacting you.

Also it only be used in our severs and not distributed or anything. Once again apologies i know this isn't a an issue

**Comment by FabioZumbi12** [comment]
You already can setup a channel to send commands. If your bot send commands to this channel like a player, will be accepted by sedb, just enable the option on config to allow bot messages.
