### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by Conjuro** [FabioZumbi12/SEDiscordBridge#4]
https://github.com/FabioZumbi12/SEDiscordBridge/blob/fe0af5424bfde40f16956e980452453c94adf989/SEDiscordBridge/SEDBControl.xaml#L32

> sames

Should be 'same'

https://github.com/FabioZumbi12/SEDiscordBridge/blob/fe0af5424bfde40f16956e980452453c94adf989/SEDiscordBridge/SEDBControl.xaml#L59

Should be 'Stopped'

https://github.com/FabioZumbi12/SEDiscordBridge/blob/fe0af5424bfde40f16956e980452453c94adf989/SEDiscordBridge/SEDBControl.xaml#L63

Should be 'Connected'

**Comment by FabioZumbi12** [comment]
Fixed on https://github.com/FabioZumbi12/SEDiscordBridge/commit/418eeaa73bc9306f5ded9f4e725ea8b0dfdc827c

Thanks for help <3
