### ISSUE TITLE
Crash when chat item's name

### ISSUE THREAD

**Issue by CaoTrongThang** [FabioZumbi12/SEDiscordBridge#40]
Sorry about my bad English ~~"

i think this is very important issue, when i show my items on chat, all players will got kick, that issue happen when the name to long or when i write any words behide ##, its will kick all players

  item-hand:
    enable: true
    # Text to show on chat when using @hand.
    # Placeholders: {hand-amount}, {hand-type}, {hand-name}
    format: '&fx{hand-amount}{hand-name} &r'
    # Placeholder to use on chat by players to show your item in hand.
    placeholder: '##'

This is my items name: &f&l[&6&l◆&f&l] PHÚC THẦN &6&lCUNG &f&l[&6&l◆&f&l] &f&l[+1]
![image](https://user-images.githubusercontent.com/51023235/68472464-31d7f880-0253-11ea-8ca0-f36bd2c362ac.png)

**Comment by FabioZumbi12** [comment]
This github and this issue is not about uchat
