### ISSUE TITLE
Error stack output in Discord

### ISSUE THREAD

**Issue by scytero** [FabioZumbi12/SEDiscordBridge#43]
Hey,

at random times, my set up bot displays an error stack in Discord:
```
System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at SEDiscordBridge.DiscordBridge.<>cDisplayClass26_0.<SendChatMessage>b0()
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---
```
There is no information other than this, what is happening. Noo specific message sent, no command, no other suspicous things can be found in the log files,. wehn this output occuures.

Not sure, if this is due to some error in my config or a bug

**Comment by FabioZumbi12** [comment]
Seems to be related with #42 , try the latest builds

**Comment by FabioZumbi12** [comment]
SEDB is now maintained by Bishbash777 on https://github.com/Bishbash777/SEDB-RELOADED
