### ISSUE TITLE
Names in Discord do not appear in-game with {p}

### ISSUE THREAD

**Issue by SpadesNeil** [FabioZumbi12/SEDiscordBridge#44]
Unless that's not the correct tag, in which case, sure would be nice to have some documentation telling what tag we are supposed to use for Discord names.
![image](https://user-images.githubusercontent.com/6484985/74690207-29754f00-51ac-11ea-910b-199d9ccc422f.png)
![image](https://user-images.githubusercontent.com/6484985/74690213-309c5d00-51ac-11ea-8a06-eea9c04c55fd.png)

**Comment by FabioZumbi12** [comment]
Use only names (uncheck `Use Discord Names`). Nicknames may have some special chars and this may cause this error (or others). Btw, this setting is working fine on my tests.
