### ISSUE TITLE
Rate Limit Exception

### ISSUE THREAD

**Issue by Casimir255** [FabioZumbi12/SEDiscordBridge#45]
Discord bot is being rate limited. Apparently sending too many messages through discord. Usually server crashes after we run profile too quickly. See logs
[Log1.txt](https://github.com/FabioZumbi12/SEDiscordBridge/files/4302931/Log1.txt)
[Log2.txt](https://github.com/FabioZumbi12/SEDiscordBridge/files/4302932/Log2.txt)

**Comment by LordTylus** [comment]
Can confirm
we had that after using !listplayers which sadly reaches the limit super fast.

> 20:31:22.9908 [INFO]   SEDiscordBridge.SEDiscordBridgePlugin: Server ran command 'listplayers -player=?????'
> 20:31:23.3501 [INFO]   Concealment: Revealed 12 grids near players.
> 20:31:30.4734 [FATAL]  Initializer: DSharpPlus.Exceptions.RateLimitException: Rate limited: 429
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at DSharpPlus.Net.DiscordApiClient.<CreateMessageAsync>d__39.MoveNext()
> DSharpPlus.Exceptions.RateLimitException: Rate limited: 429
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at DSharpPlus.Net.DiscordApiClient.<CreateMessageAsync>d__39.MoveNext()

An error message from Discord should NEVER cause a server crash.

**Comment by FabioZumbi12** [comment]
The latest pre-release on https://github.com/FabioZumbi12/SEDiscordBridge/releases should cover this and dont crash the server
