### ISSUE TITLE
Names blacked out in game since Frostbite patch

### ISSUE THREAD

**Issue by kontu** [FabioZumbi12/SEDiscordBridge#47]
Names are blacked/blurred out in game on broadcast messages since the Frostbite patch using this plugin.

In the image below; the "Good.bot" line is from another server using this plugin, the science test is a message sent from discord.

https://i.imgur.com/zLyckgA.png

**Comment by FabioZumbi12** [comment]
Its not a SEDB issue :/

**Comment by kontu** [comment]
It's since been fixed by the torch devs -- but we also definitely fixed it with a patch to SEDB until they did :) no worries.
