### ISSUE TITLE
Names still do not show up

### ISSUE THREAD

**Issue by GarretSidzaka** [FabioZumbi12/SEDiscordBridge#49]
Hello,
In the new release there is a {p} to signifiy player name in a chat message format.  However the {p} is not getting replaced with "Garret Sidzaka" (my username} when i chat from discord to the game.  The bot simply skips it so that **{p}** only shows up as ****

thank you

**Comment by FabioZumbi12** [comment]
Maybe the discord api dont support some Nicknames special chars, i recommend to uncheck the config option to use nicknames instead username. usernames its working fine btw!
