### ISSUE TITLE
SEDiscordBridge Reloaded 1.0.1 and 1.0.2 will not unzip

### ISSUE THREAD

**Issue by XeroCreator** [FabioZumbi12/SEDiscordBridge#50]
SEDiscordBridge Reloaded 1.0.1 and 1.0.2 will not unzip

Windows 10 professional.

Winrar, 7zip, and windows built-in manager will not unzip and says the folder is empty or 'corrupt'.
Deleting the systemmemory.dll allows me to unzip the files.

I can open the archive with winrar and 7z and see the files are there.

I was able to 'copy' the files from 7z to a blank folder inside 7z.
I was able to 'extract' the files from inside 7z to a blank folder as well.
However, right click options don't seem to work for windows, 7z, or winrar.
Only have the issue w/ sedb reloaded version

7z gives a slightly different error saying 'there is some data at the end of the payload file'
when trying to use right click 'extract' option.

Re-zipping w/ windows and unzipping after seems fine.

Edit: managed to get it all extracted without issue.
7z seems to work periodically, I believe the issue stems from the folder being zipped by 7z and not the windows built-in zip program.

I could be wrong, but it works fine w/ my zip.
[sediscordbridge - reloaded-v1.0.2 - WORKING.zip](https://github.com/FabioZumbi12/SEDiscordBridge/files/4534960/sediscordbridge.-.reloaded-v1.0.2.-.WORKING.zip)

**Comment by FabioZumbi12** [comment]
Its normal. Its an isue with the plugin itself and yes with Autoupdater/Torch site, and its not an issue since you dont need to extract the zip to run, just leave on plugin folder and it will loads!
