### ISSUE TITLE
Faction Chat messages D2G are being read in global

### ISSUE THREAD

**Issue by GarretSidzaka** [FabioZumbi12/SEDiscordBridge#51]
Hello,
When a user in the faction chat channel on discord messages D2G (discord to game) it is read off in global chat in-game.   G2D (game to discord) faction messages displaying properly in discord.

For example:  if a faction leader is on discord and talks to his members, its going to global chat, so he gets no secrecy.   However, he could read his faction mates conversation, as long as he doesn't reply.
Thank you.

**Comment by FabioZumbi12** [comment]
SEDB is now maintained by Bishbash777 on https://github.com/Bishbash777/SEDB-RELOADED
