### ISSUE TITLE
[US][Improvement] Save in encrypted hash discord bot token.

### ISSUE THREAD

**Issue by szczepix** [FabioZumbi12/SEDiscordBridge#7]
As a Server Owner, I want save my discord bot token encrypted in plugin config, so that SE servers admins can't read it.

**Comment by FabioZumbi12** [comment]
On plugin config page i can add an option to hide the token and can only be accessed by config file, ok?

**Comment by szczepix** [comment]
ok is enough for now 👍 
but look on https://github.com/Jimmacle/torch-rcon-plugin and how Jimmacle saving Rcon password :)

**Comment by FabioZumbi12** [comment]
Added option to hide from config file.
